### ISSUE TITLE
May you clarify how different your paper is from this paper: Investigating the Working of Text Classifiers

### ISSUE THREAD

**Issue by Sandy4321** [Cimagroup/Experiments-Representative-datasets#1]
https://github.com/DevSinghSachan/investigating-text-classifiers
https://arxiv.org/abs/1801.06261
Investigating the Working of Text Classifiers
May you clarify how different your paper is from this paper: Investigating the Working of Text Classifiers

**Comment by EduPH** [comment]
Hi!, 
I would need to read it carefully but my first impression is that they focus on natural language processing datasets. Using then a methodology really intrinsic to the type of data: lexicons....
In our case, we are dealing with any n-dimensional dataset, and, using a nearness condition, reduce the size of data, i.e., the number of points.  Then, we propose as a tool to measure the similarity of two different datasets both Hausdorff distance and Bottleneck distance. 

Besides, it seems that in the paper you provide, they are trying to discriminate if MLP can really generalize datasets of NLP or not. 

Thank you for your interest in our paper. You can find it [here](https://128.84.21.199/abs/1903.08519).

Greetings

**Comment by Sandy4321** [comment]
great thanks
you explained very well
do you have this  kind of clear explanation in written for example presentation slides: less scientific but more practicable?

**Comment by EduPH** [comment]
Not yet. However, if I do some slides, I would add them to this repository.
